"""Coverage-guided fuzzing of the parsers that read input this does not control.

Each target feeds Atheris-generated bytes to one parser: the TDS packet,
PRELOGIN, LOGIN7, SQL batch and RPC readers a client's bytes reach before
anything is authenticated, the SQL parser, and the JSON, XML, HTML and CSV
readers a source's response goes through. tests/fuzz_targets.py says what
each target calls and which error it may raise; anything else, a crash or a
hang, is a finding, and Atheris writes the input to a crash-* file.

    python fuzz/fuzz_parsers.py <target> [libFuzzer options] [corpus dirs]

    python fuzz/fuzz_parsers.py login7 -max_total_time=60 tests/fuzz_corpus/login7

The .github/workflows/fuzz.yml workflow runs each target, seeded from
tests/fuzz_corpus/<target>. A finding becomes a regression seed in that
directory, which tests/test_fuzz_corpus.py replays on every CI run.
"""

import sys
from pathlib import Path

import atheris

# The targets live with the tests, which the sdist ships.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

with atheris.instrument_imports():
    from tests.fuzz_targets import TARGETS


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in TARGETS:
        sys.exit(f"usage: fuzz_parsers.py <{'|'.join(TARGETS)}> [libFuzzer options]")
    target = TARGETS[sys.argv[1]]
    atheris.Setup([sys.argv[0], *sys.argv[2:]], target)
    atheris.Fuzz()


if __name__ == "__main__":
    main()
